### ISSUE TITLE
autoredirect?

### ISSUE THREAD

**Issue by charlesdevelops** [zollf/csmarks-redirect#1]
its a great tool and I use it all the time but I feel like a simple dns redirect would be easier than making it a button; cant the site (or dns records) be updated to do it automatically? Maybe get the user to configure this on the site (checkbox for all future visits etc) if they want this or not.

**Comment by zollf** [comment]
@charlesdevelops For context: this was a joke site that we used to be able to access csmarks because we never could find the link. I guess UWA never fixed it after all these years

Unfortunately an automatic redirect would make Googlebot follow and treat https://secure.csse.uwa.edu.au/run/csmarks SEO as ours. See: https://developers.google.com/search/docs/crawling-indexing/301-redirects. This won't rank too well or be easily searchable on Google. 

Happy to make an auto redirect system based on user preference.

**Comment by zollf** [comment]
Hey @charlesdevelops ,

I've added the auto-redirect feature now. Once you click on the button, it will remember your decision and auto-redirect you every time. Let me know what you think and if you have any issues, thanks.
